window.onload = function(){
    document.getElementById("1").onclick=function(){
      document.getElementById("tło1").style.display = "block";
      document.getElementById("tło2").style.display = "none";
      document.getElementById("tlo3").style.display = "none";
      document.getElementById("tlo4").style.display = "none";
      document.getElementById("tlo5").style.display = "none";
      document.getElementById("tlo6").style.display = "none";
      document.getElementById("tlo7").style.display = "none";
      document.getElementById("tlo8").style.display = "none";
      document.getElementById("tlo9").style.display = "none";
      document.getElementById("tlo10").style.display = "none";
      document.getElementById("tlo11").style.display = "none";
          document.getElementById("tlo12").style.display = "none";
          document.getElementById("tlo13").style.display = "none";
          document.getElementById("tlo14").style.display = "none";
		
    }
    document.getElementById("2").onclick=function(){
      document.getElementById("tło1").style.display = "none";
          document.getElementById("tło2").style.display = "block";
          document.getElementById("tlo3").style.display = "none";
          document.getElementById("tlo4").style.display = "none";
          document.getElementById("tlo5").style.display = "none";
          document.getElementById("tlo6").style.display = "none";
          document.getElementById("tlo7").style.display = "none";
          document.getElementById("tlo8").style.display = "none";
          document.getElementById("tlo9").style.display = "none";
          document.getElementById("tlo10").style.display = "none";
          document.getElementById("tlo11").style.display = "none";
          document.getElementById("tlo12").style.display = "none";
          document.getElementById("tlo13").style.display = "none";
          document.getElementById("tlo14").style.display = "none";
    }
    document.getElementById("3").onclick=function(){
      document.getElementById("tło1").style.display = "none";
      document.getElementById("tło2").style.display = "none";
      document.getElementById("tlo3").style.display = "block";
      document.getElementById("tlo4").style.display = "none";
      document.getElementById("tlo5").style.display = "none";
      document.getElementById("tlo6").style.display = "none";
      document.getElementById("tlo7").style.display = "none";
      document.getElementById("tlo8").style.display = "none";
      document.getElementById("tlo9").style.display = "none";
      document.getElementById("tlo10").style.display = "none";
      document.getElementById("tlo11").style.display = "none";
          document.getElementById("tlo12").style.display = "none";
          document.getElementById("tlo13").style.display = "none";
          document.getElementById("tlo14").style.display = "none";
    }
      document.getElementById("4").onclick=function(){
        document.getElementById("tło1").style.display = "none";
        document.getElementById("tło2").style.display = "none";
        document.getElementById("tlo3").style.display = "none";
        document.getElementById("tlo4").style.display = "block";
        document.getElementById("tlo5").style.display = "none";
        document.getElementById("tlo6").style.display = "none";
        document.getElementById("tlo7").style.display = "none";
        document.getElementById("tlo8").style.display = "none";
        document.getElementById("tlo9").style.display = "none";
        document.getElementById("tlo10").style.display = "none";
        document.getElementById("tlo11").style.display = "none";
          document.getElementById("tlo12").style.display = "none";
          document.getElementById("tlo13").style.display = "none";
          document.getElementById("tlo14").style.display = "none";
      }
        document.getElementById("5").onclick=function(){
          document.getElementById("tło1").style.display = "none";
          document.getElementById("tło2").style.display = "none";
          document.getElementById("tlo3").style.display = "none";
          document.getElementById("tlo4").style.display = "none";
          document.getElementById("tlo5").style.display = "block";
          document.getElementById("tlo6").style.display = "none";
          document.getElementById("tlo7").style.display = "none";
          document.getElementById("tlo8").style.display = "none";
          document.getElementById("tlo9").style.display = "none";
          document.getElementById("tlo10").style.display = "none";
          document.getElementById("tlo11").style.display = "none";
          document.getElementById("tlo12").style.display = "none";
          document.getElementById("tlo13").style.display = "none";
          document.getElementById("tlo14").style.display = "none";
        }
        document.getElementById("6").onclick=function(){
          document.getElementById("tło1").style.display = "none";
          document.getElementById("tło2").style.display = "none";
          document.getElementById("tlo3").style.display = "none";
          document.getElementById("tlo4").style.display = "none";
          document.getElementById("tlo5").style.display = "none";
          document.getElementById("tlo6").style.display = "block";
          document.getElementById("tlo7").style.display = "none";
          document.getElementById("tlo8").style.display = "none";
          document.getElementById("tlo9").style.display = "none";
          document.getElementById("tlo10").style.display = "none";
          document.getElementById("tlo11").style.display = "none";
          document.getElementById("tlo12").style.display = "none";
          document.getElementById("tlo13").style.display = "none";
          document.getElementById("tlo14").style.display = "none";
        }
        document.getElementById("7").onclick=function(){
          document.getElementById("tło1").style.display = "none";
          document.getElementById("tło2").style.display = "none";
          document.getElementById("tlo3").style.display = "none";
          document.getElementById("tlo4").style.display = "none";
          document.getElementById("tlo5").style.display = "none";
          document.getElementById("tlo6").style.display = "none";
          document.getElementById("tlo7").style.display = "block";
          document.getElementById("tlo8").style.display = "none";
          document.getElementById("tlo9").style.display = "none";
          document.getElementById("tlo10").style.display = "none";
          document.getElementById("tlo11").style.display = "none";
          document.getElementById("tlo12").style.display = "none";
          document.getElementById("tlo13").style.display = "none";
          document.getElementById("tlo14").style.display = "none";
        }
        document.getElementById("8").onclick=function(){
          document.getElementById("tło1").style.display = "none";
          document.getElementById("tło2").style.display = "none";
          document.getElementById("tlo3").style.display = "none";
          document.getElementById("tlo4").style.display = "none";
          document.getElementById("tlo5").style.display = "none";
          document.getElementById("tlo6").style.display = "none";
          document.getElementById("tlo7").style.display = "none";
          document.getElementById("tlo8").style.display = "block";
          document.getElementById("tlo9").style.display = "none";
          document.getElementById("tlo10").style.display = "none";
          document.getElementById("tlo11").style.display = "none";
          document.getElementById("tlo12").style.display = "none";
          document.getElementById("tlo13").style.display = "none";
          document.getElementById("tlo14").style.display = "none";
        }
        document.getElementById("9").onclick=function(){
          document.getElementById("tło1").style.display = "none";
          document.getElementById("tło2").style.display = "none";
          document.getElementById("tlo3").style.display = "none";
          document.getElementById("tlo4").style.display = "none";
          document.getElementById("tlo5").style.display = "none";
          document.getElementById("tlo6").style.display = "none";
          document.getElementById("tlo7").style.display = "none";
          document.getElementById("tlo8").style.display = "none";
          document.getElementById("tlo9").style.display = "block";
          document.getElementById("tlo10").style.display = "none";
          document.getElementById("tlo11").style.display = "none";
          document.getElementById("tlo12").style.display = "none";
          document.getElementById("tlo13").style.display = "none";
          document.getElementById("tlo14").style.display = "none";
        }
        document.getElementById("10").onclick=function(){
          document.getElementById("tło1").style.display = "none";
          document.getElementById("tło2").style.display = "none";
          document.getElementById("tlo3").style.display = "none";
          document.getElementById("tlo4").style.display = "none";
          document.getElementById("tlo5").style.display = "none";
          document.getElementById("tlo6").style.display = "none";
          document.getElementById("tlo7").style.display = "none";
          document.getElementById("tlo8").style.display = "none";
          document.getElementById("tlo9").style.display = "none";
          document.getElementById("tlo10").style.display = "block";
          document.getElementById("tlo11").style.display = "none";
          document.getElementById("tlo12").style.display = "none";
          document.getElementById("tlo13").style.display = "none";
          document.getElementById("tlo14").style.display = "none";
        
        }
        document.getElementById("11").onclick=function(){
          document.getElementById("tło1").style.display = "none";
          document.getElementById("tło2").style.display = "none";
          document.getElementById("tlo3").style.display = "none";
          document.getElementById("tlo4").style.display = "none";
          document.getElementById("tlo5").style.display = "none";
          document.getElementById("tlo6").style.display = "none";
          document.getElementById("tlo7").style.display = "none";
          document.getElementById("tlo8").style.display = "none";
          document.getElementById("tlo9").style.display = "none";
          document.getElementById("tlo10").style.display = "none";
          document.getElementById("tlo11").style.display = "block";
          document.getElementById("tlo12").style.display = "none";
          document.getElementById("tlo13").style.display = "none";
          document.getElementById("tlo14").style.display = "none";
        }
        document.getElementById("12").onclick=function(){
          document.getElementById("tło1").style.display = "none";
          document.getElementById("tło2").style.display = "none";
          document.getElementById("tlo3").style.display = "none";
          document.getElementById("tlo4").style.display = "none";
          document.getElementById("tlo5").style.display = "none";
          document.getElementById("tlo6").style.display = "none";
          document.getElementById("tlo7").style.display = "none";
          document.getElementById("tlo8").style.display = "none";
          document.getElementById("tlo9").style.display = "none";
          document.getElementById("tlo10").style.display = "none";
          document.getElementById("tlo11").style.display = "none";
          document.getElementById("tlo12").style.display = "block";
          document.getElementById("tlo13").style.display = "none";
          document.getElementById("tlo14").style.display = "none";
        }
        document.getElementById("13").onclick=function(){
          document.getElementById("tło1").style.display = "none";
          document.getElementById("tło2").style.display = "none";
          document.getElementById("tlo3").style.display = "none";
          document.getElementById("tlo4").style.display = "none";
          document.getElementById("tlo5").style.display = "none";
          document.getElementById("tlo6").style.display = "none";
          document.getElementById("tlo7").style.display = "none";
          document.getElementById("tlo8").style.display = "none";
          document.getElementById("tlo9").style.display = "none";
          document.getElementById("tlo10").style.display = "none";
          document.getElementById("tlo11").style.display = "none";
          document.getElementById("tlo12").style.display = "none";
          document.getElementById("tlo13").style.display = "block";
          document.getElementById("tlo14").style.display = "none";
        }
        document.getElementById("14").onclick=function(){
          document.getElementById("tło1").style.display = "none";
          document.getElementById("tło2").style.display = "none";
          document.getElementById("tlo3").style.display = "none";
          document.getElementById("tlo4").style.display = "none";
          document.getElementById("tlo5").style.display = "none";
          document.getElementById("tlo6").style.display = "none";
          document.getElementById("tlo7").style.display = "none";
          document.getElementById("tlo8").style.display = "none";
          document.getElementById("tlo9").style.display = "none";
          document.getElementById("tlo10").style.display = "none";
          document.getElementById("tlo11").style.display = "none";
          document.getElementById("tlo12").style.display = "none";
          document.getElementById("tlo13").style.display = "none";
          document.getElementById("tlo14").style.display = "block";
        }}